program =
  | statement+ EOF ;

statement =
  | "let" IDENT "=" expr ";"
  | "print" expr ";"
  | "if" "(" epxr ")" "{" statement* "}" [else_stmt]
  ;

else_stmt =
  | "else" "{" statement* "}"
  ;

expr =
  | relation
  ;

equal =
  | relation ( ("==" | "!=") relation )*
  ;

relation =
  | term ( ("<" | "<=" | ">" | ">=") term )*
  ;

term =
  | factor ( ("+" | "-") factor )*
  ;

factor =
  | primary ( ("*" | "/" | "%") primary )*
  ;

primary =
  | NUMBER
  | IDENT
  | "(" expr ")"
  ;


NUMBER = [0-9]+ ;
IDENT = [a-zA-Z_][a-zA-Z0-9_]* ;
