program =
  | statment+ EOF ;

statment =
  | "let" IDENT "=" expr ";"
  | expr ";"
  ;

expr =
  | term
  ;

term =
  | factor ( ("+" | "-") factor )*
  ;

factor =
  | primary ( ("*" | "/") primary )*
  ;

primary =
  | NUMBER
  | IDENT
  | "(" expr ")"
  ;


NUMBER = [0-9]+ ;
IDENT = [a-zA-Z_][a-zA-Z0-9_]* ;
